const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  getClientId:   ()    => ipcRenderer.invoke('get-client-id'),
  saveClientId:  (id)  => ipcRenderer.invoke('save-client-id', id),
  getSavedToken: ()    => ipcRenderer.invoke('get-saved-token'),
  login:         ()    => ipcRenderer.invoke('spotify-login'),
  refreshToken:  ()    => ipcRenderer.invoke('refresh-token'),
  logout:        ()    => ipcRenderer.invoke('logout'),
  fetchLyrics:   (id, tok) => ipcRenderer.invoke('fetch-lyrics', id, tok),
  launchSpotify: ()    => ipcRenderer.invoke('launch-spotify'),
  minimize:      ()    => ipcRenderer.send('window-minimize'),
  maximize:      ()    => ipcRenderer.send('window-maximize'),
  close:         ()    => ipcRenderer.send('window-close'),
  toggleFullscreen: () => ipcRenderer.send('window-fullscreen'),
  setAppIcon:    (d)   => ipcRenderer.send('set-app-icon', d),
  showMiniPlayer:     (data) => ipcRenderer.send('mini:show', data),
  hideMiniPlayer:     ()     => ipcRenderer.send('mini:hide'),
  updateMiniPlayer:   (data) => ipcRenderer.send('mini:update', data),
  updateMiniLyric:    (text) => ipcRenderer.send('mini:lyric', text),
  onMiniAction:       (cb)   => ipcRenderer.on('mini:action',        (_, type) => cb(type)),
  onTrayAction:       (cb)   => ipcRenderer.on('tray:action',        (_, type) => cb(type)),
  onHotkey:           (cb)   => ipcRenderer.on('hotkey',             (_, type) => cb(type)),
  onUpdateAvailable:  (cb)   => ipcRenderer.on('update:available',   () => cb()),
  onUpdateDownloaded: (cb)   => ipcRenderer.on('update:downloaded',  () => cb()),
  installUpdate:      ()     => ipcRenderer.send('update:install'),
  updateTray:         (data) => ipcRenderer.send('tray:update',      data),
  updateDiscord:      (data) => ipcRenderer.send('discord:update',   data),
  setCloseBehavior:   (val)  => ipcRenderer.send('set-close-to-tray', val),
  getCloseBehavior:   ()     => ipcRenderer.invoke('get-close-to-tray'),
  showImmersive:           (d) => ipcRenderer.send('immersive:show', d),
  hideImmersive:           ()  => ipcRenderer.send('immersive:hide'),
  updateImmersive:         (d) => ipcRenderer.send('immersive:update', d),
  updateImmersiveLyrics:   (d) => ipcRenderer.send('immersive:lyrics', d),
  updateImmersiveProgress: (d) => ipcRenderer.send('immersive:progress', d),
  updateImmersiveQueue:    (d) => ipcRenderer.send('immersive:queue', d),
  setImmersiveGlassMode:   (m) => ipcRenderer.send('immersive:glass-mode', m),
  onImmersiveAction:       (cb) => ipcRenderer.on('immersive:action', (_, t) => cb(t)),
  onFullscreenState:       (cb) => ipcRenderer.on('fullscreen-state', (_, v) => cb(v)),
});
